(() => {
  "use strict";
  let apiRef=null,overlay=null,state={items:[]};
  function load(api){const s=api.storage.get({items:[]});return{items:Array.isArray(s?.items)?s.items:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){ return null; }
  function render(){const list=overlay?.querySelector("[data-check-list]"),sum=overlay?.querySelector("[data-check-sum]");if(!list)return;list.textContent="";let done=0;state.items.forEach(item=>{const row=document.createElement("div");row.className="tm-check-row"+(item.done?" done":"");const b=document.createElement("button");b.className="tm-check-box"+(item.done?" on":"");b.textContent=item.done?"✓":"";b.addEventListener("click",()=>{item.done=!item.done;save();render();});const t=document.createElement("div");t.className="tm-check-text";t.textContent=item.text;const d=document.createElement("button");d.className="tm-check-del";d.textContent="删除";d.addEventListener("click",()=>{state.items=state.items.filter(x=>x.id!==item.id);save();render();});row.append(b,t,d);list.appendChild(row);if(item.done)done++;});sum.textContent="完成 "+done+" / "+state.items.length;}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"checklist",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-check-ov";const box=document.createElement("section");box.className="tm-check";box.innerHTML=`<div class="tm-check-head"><h3>☑️ TODO 清单</h3><button type="button">×</button></div><div class="tm-check-add"><input maxlength="60" placeholder="添加独立待办"><button type="button">添加</button></div><div data-check-list></div><div class="tm-check-summary" data-check-sum></div>`;overlay.appendChild(box);document.body.appendChild(overlay);const input=box.querySelector(".tm-check-add input"),add=box.querySelector(".tm-check-add button");const create=()=>{const text=input.value.trim();if(!text)return;state.items.push({id:Date.now()+Math.random(),text:text.slice(0,60),done:false});input.value="";save();render();};add.addEventListener("click",create);input.addEventListener("keydown",e=>{if(e.key==="Enter")create();});box.querySelector(".tm-check-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"☑️",label:"TODO",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-check-style")?.remove();apiRef=null;};},open});
})();