(() => {
  "use strict";
  let apiRef=null,overlay=null,state={items:[]};
  function load(api){const s=api.storage.get({items:[]});return{items:Array.isArray(s?.items)?s.items:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){if(document.getElementById("tm-check-style"))return;const s=document.createElement("style");s.id="tm-check-style";s.textContent=`
  .tm-check-ov{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;background:rgba(2,6,23,.74);backdrop-filter:blur(5px)}.tm-check-ov.open{display:flex}.tm-check{width:min(520px,94vw);max-height:88vh;overflow:auto;background:#111827;border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:18px;color:#fff;font-family:"Segoe UI","Microsoft YaHei",sans-serif}.tm-check-head{display:flex;justify-content:space-between;align-items:center}.tm-check-head h3{margin:0}.tm-check-head button{border:0;background:transparent;color:#94a3b8;font-size:24px;cursor:pointer}.tm-check-add{display:flex;gap:8px;margin:14px 0}.tm-check-add input{flex:1;border:1px solid #334155;border-radius:9px;background:#0b1220;color:#fff;padding:10px}.tm-check-add button{border:0;border-radius:9px;background:#4f46e5;color:#fff;padding:0 14px}.tm-check-row{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:9px 4px;border-bottom:1px solid rgba(255,255,255,.07)}.tm-check-row.done .tm-check-text{text-decoration:line-through;color:#64748b}.tm-check-box{width:26px;height:26px;border-radius:8px;border:1px solid #475569;background:#0f172a;color:#fff;cursor:pointer}.tm-check-box.on{background:#16a34a}.tm-check-del{border:0;background:transparent;color:#64748b;cursor:pointer}.tm-check-summary{font-size:11px;color:#94a3b8;margin-top:12px}
  `;document.head.appendChild(s);}
  function render(){const list=overlay?.querySelector("[data-check-list]"),sum=overlay?.querySelector("[data-check-sum]");if(!list)return;list.textContent="";let done=0;state.items.forEach(item=>{const row=document.createElement("div");row.className="tm-check-row"+(item.done?" done":"");const b=document.createElement("button");b.className="tm-check-box"+(item.done?" on":"");b.textContent=item.done?"✓":"";b.addEventListener("click",()=>{item.done=!item.done;save();render();});const t=document.createElement("div");t.className="tm-check-text";t.textContent=item.text;const d=document.createElement("button");d.className="tm-check-del";d.textContent="删除";d.addEventListener("click",()=>{state.items=state.items.filter(x=>x.id!==item.id);save();render();});row.append(b,t,d);list.appendChild(row);if(item.done)done++;});sum.textContent="完成 "+done+" / "+state.items.length;}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"checklist",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-check-ov";const box=document.createElement("section");box.className="tm-check";box.innerHTML=`<div class="tm-check-head"><h3>☑️ TODO 清单</h3><button type="button">×</button></div><div class="tm-check-add"><input maxlength="60" placeholder="添加独立待办"><button type="button">添加</button></div><div data-check-list></div><div class="tm-check-summary" data-check-sum></div>`;overlay.appendChild(box);document.body.appendChild(overlay);const input=box.querySelector(".tm-check-add input"),add=box.querySelector(".tm-check-add button");const create=()=>{const text=input.value.trim();if(!text)return;state.items.push({id:Date.now()+Math.random(),text:text.slice(0,60),done:false});input.value="";save();render();};add.addEventListener("click",create);input.addEventListener("keydown",e=>{if(e.key==="Enter")create();});box.querySelector(".tm-check-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"☑️",label:"TODO",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-check-style")?.remove();apiRef=null;};},open});
})();