(() => {
  "use strict";
  let apiRef=null,overlay=null,state={entries:{}};
  const today=()=>new Date().toISOString().slice(0,10);
  function load(api){const s=api.storage.get({entries:{}});return{entries:s?.entries&&typeof s.entries==="object"?s.entries:{}};}
  function save(){apiRef?.storage.set(state);}
  function style(){ return null; }
  function render(){if(!overlay)return;const e=state.entries[today()]||{};overlay.querySelector("[data-r1]").value=e.done||"";overlay.querySelector("[data-r2]").value=e.problem||"";overlay.querySelector("[data-r3]").value=e.tomorrow||"";const h=overlay.querySelector("[data-rhist]");h.textContent="";Object.keys(state.entries).sort().reverse().slice(0,7).forEach(k=>{const d=document.createElement("div");d.className="tm-rev-item";d.textContent=k+" · "+((state.entries[k].done||"").slice(0,40)||"无摘要");h.appendChild(d);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"daily-review",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-rev-ov";const box=document.createElement("section");box.className="tm-rev";box.innerHTML=`<div class="tm-rev-head"><h3>🌙 每日复盘</h3><button type="button">×</button></div><label>今天完成了什么？<textarea data-r1></textarea></label><label>今天最大的困难/问题？<textarea data-r2></textarea></label><label>明天最重要的一件事？<textarea data-r3></textarea></label><button class="tm-rev-save" type="button">保存今天的复盘</button><div class="tm-rev-history" data-rhist></div>`;overlay.appendChild(box);document.body.appendChild(overlay);box.querySelector(".tm-rev-save").addEventListener("click",()=>{state.entries[today()]={done:box.querySelector("[data-r1]").value.slice(0,2000),problem:box.querySelector("[data-r2]").value.slice(0,2000),tomorrow:box.querySelector("[data-r3]").value.slice(0,2000),updatedAt:Date.now()};save();api.host.toast("今日复盘已保存");render();});box.querySelector(".tm-rev-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"🌙",label:"复盘",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-review-style")?.remove();apiRef=null;};},open});
})();