(() => {
  "use strict";
  let apiRef=null,overlay=null,state={goals:[]};
  function load(api){const s=api.storage.get({goals:[]});return{goals:Array.isArray(s?.goals)?s.goals:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){if(document.getElementById("tm-goal-style"))return;const s=document.createElement("style");s.id="tm-goal-style";s.textContent=`
  .tm-goal-ov{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;background:rgba(2,6,23,.74);backdrop-filter:blur(5px)}.tm-goal-ov.open{display:flex}.tm-goal{width:min(560px,94vw);max-height:88vh;overflow:auto;background:#111827;border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:18px;color:#fff;font-family:"Segoe UI","Microsoft YaHei",sans-serif}.tm-goal-head{display:flex;justify-content:space-between;align-items:center}.tm-goal-head h3{margin:0}.tm-goal-head button{border:0;background:transparent;color:#94a3b8;font-size:24px}.tm-goal-add{display:grid;grid-template-columns:1fr 90px auto;gap:8px;margin:14px 0}.tm-goal-add input{min-width:0;border:1px solid #334155;border-radius:9px;background:#0b1220;color:#fff;padding:9px}.tm-goal-add button{border:0;border-radius:9px;background:#059669;color:#fff;padding:0 12px}.tm-goal-card{padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:13px;background:rgba(30,41,59,.6);margin-bottom:9px}.tm-goal-top{display:flex;justify-content:space-between;gap:10px}.tm-goal-name{font-weight:700}.tm-goal-bar{height:9px;background:#1f2937;border-radius:999px;overflow:hidden;margin:9px 0}.tm-goal-fill{height:100%;background:linear-gradient(90deg,#10b981,#22c55e)}.tm-goal-controls{display:flex;align-items:center;gap:8px}.tm-goal-controls input{width:90px;border:1px solid #334155;border-radius:8px;background:#0b1220;color:#fff;padding:6px}.tm-goal-del{margin-left:auto;border:0;background:transparent;color:#f87171}
  `;document.head.appendChild(s);}
  function render(){const list=overlay?.querySelector("[data-goal-list]");if(!list)return;list.textContent="";state.goals.forEach(g=>{const card=document.createElement("div");card.className="tm-goal-card";const top=document.createElement("div");top.className="tm-goal-top";const name=document.createElement("div");name.className="tm-goal-name";name.textContent=g.name;const pct=document.createElement("div");pct.textContent=Math.round(Math.min(100,(Number(g.current)||0)/(Number(g.target)||1)*100))+"%";top.append(name,pct);const bar=document.createElement("div");bar.className="tm-goal-bar";const fill=document.createElement("div");fill.className="tm-goal-fill";fill.style.width=pct.textContent;bar.appendChild(fill);const ctr=document.createElement("div");ctr.className="tm-goal-controls";const inp=document.createElement("input");inp.type="number";inp.min="0";inp.value=g.current||0;inp.addEventListener("change",()=>{g.current=Math.max(0,Number(inp.value)||0);save();render();});const txt=document.createElement("span");txt.textContent="/ "+g.target;const del=document.createElement("button");del.className="tm-goal-del";del.textContent="删除";del.addEventListener("click",()=>{state.goals=state.goals.filter(x=>x.id!==g.id);save();render();});ctr.append(inp,txt,del);card.append(top,bar,ctr);list.appendChild(card);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"goals",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-goal-ov";const box=document.createElement("section");box.className="tm-goal";box.innerHTML=`<div class="tm-goal-head"><h3>🎯 目标进度</h3><button type="button">×</button></div><div class="tm-goal-add"><input maxlength="50" placeholder="目标名称"><input type="number" min="1" placeholder="目标值"><button type="button">添加</button></div><div data-goal-list></div>`;overlay.appendChild(box);document.body.appendChild(overlay);const inputs=box.querySelectorAll(".tm-goal-add input"),add=box.querySelector(".tm-goal-add button");add.addEventListener("click",()=>{const name=inputs[0].value.trim(),target=Math.max(1,Number(inputs[1].value)||0);if(!name||!target)return;state.goals.push({id:Date.now()+Math.random(),name:name.slice(0,50),target,current:0});inputs[0].value="";inputs[1].value="";save();render();});box.querySelector(".tm-goal-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"🎯",label:"目标",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-goal-style")?.remove();apiRef=null;};},open});
})();