(() => {
  "use strict";
  let apiRef=null,overlay=null,state={options:[]};
  function load(api){const s=api.storage.get({options:[]});return{options:Array.isArray(s?.options)?s.options:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){if(document.getElementById("tm-rand-style"))return;const s=document.createElement("style");s.id="tm-rand-style";s.textContent=`
  .tm-rand-ov{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;background:rgba(2,6,23,.74);backdrop-filter:blur(5px)}.tm-rand-ov.open{display:flex}.tm-rand{width:min(460px,94vw);background:#111827;border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:18px;color:#fff;font-family:"Segoe UI","Microsoft YaHei",sans-serif}.tm-rand-head{display:flex;justify-content:space-between}.tm-rand-head h3{margin:0}.tm-rand-head button{border:0;background:transparent;color:#94a3b8;font-size:24px}.tm-rand-add{display:flex;gap:8px;margin:14px 0}.tm-rand-add input{flex:1;border:1px solid #334155;border-radius:9px;background:#0b1220;color:#fff;padding:9px}.tm-rand-add button{border:0;border-radius:9px;background:#2563eb;color:#fff;padding:0 12px}.tm-rand-opt{display:flex;justify-content:space-between;gap:8px;padding:7px;border-bottom:1px solid rgba(255,255,255,.06)}.tm-rand-opt button{border:0;background:transparent;color:#f87171}.tm-rand-result{text-align:center;font-size:26px;font-weight:800;color:#fde68a;min-height:44px;margin:18px 0}.tm-rand-pick{width:100%;border:0;border-radius:11px;background:linear-gradient(135deg,#f59e0b,#ef4444);color:#fff;padding:11px;font-weight:700}
  `;document.head.appendChild(s);}
  function render(){const list=overlay?.querySelector("[data-rlist]");if(!list)return;list.textContent="";state.options.forEach((o,i)=>{const row=document.createElement("div");row.className="tm-rand-opt";const t=document.createElement("span");t.textContent=o;const d=document.createElement("button");d.textContent="删除";d.addEventListener("click",()=>{state.options.splice(i,1);save();render();});row.append(t,d);list.appendChild(row);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"random-picker",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-rand-ov";const box=document.createElement("section");box.className="tm-rand";box.innerHTML=`<div class="tm-rand-head"><h3>🎲 随机决策</h3><button type="button">×</button></div><div class="tm-rand-add"><input maxlength="50" placeholder="输入一个选项"><button type="button">添加</button></div><div data-rlist></div><div class="tm-rand-result" data-result>准备好了吗？</div><button class="tm-rand-pick" type="button">随机选一个</button>`;overlay.appendChild(box);document.body.appendChild(overlay);const input=box.querySelector(".tm-rand-add input"),add=box.querySelector(".tm-rand-add button");const create=()=>{const v=input.value.trim();if(!v)return;state.options.push(v.slice(0,50));input.value="";save();render();};add.addEventListener("click",create);input.addEventListener("keydown",e=>{if(e.key==="Enter")create();});box.querySelector(".tm-rand-pick").addEventListener("click",()=>{const r=box.querySelector("[data-result]");r.textContent=state.options.length?state.options[Math.floor(Math.random()*state.options.length)]:"先添加至少一个选项";});box.querySelector(".tm-rand-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"🎲",label:"随机",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-rand-style")?.remove();apiRef=null;};},open});
})();