(() => {
  "use strict";
  let apiRef=null,overlay=null,state={options:[]};
  function load(api){const s=api.storage.get({options:[]});return{options:Array.isArray(s?.options)?s.options:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){ return null; }
  function render(){const list=overlay?.querySelector("[data-rlist]");if(!list)return;list.textContent="";state.options.forEach((o,i)=>{const row=document.createElement("div");row.className="tm-rand-opt";const t=document.createElement("span");t.textContent=o;const d=document.createElement("button");d.textContent="删除";d.addEventListener("click",()=>{state.options.splice(i,1);save();render();});row.append(t,d);list.appendChild(row);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"random-picker",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-rand-ov";const box=document.createElement("section");box.className="tm-rand";box.innerHTML=`<div class="tm-rand-head"><h3>🎲 随机决策</h3><button type="button">×</button></div><div class="tm-rand-add"><input maxlength="50" placeholder="输入一个选项"><button type="button">添加</button></div><div data-rlist></div><div class="tm-rand-result" data-result>准备好了吗？</div><button class="tm-rand-pick" type="button">随机选一个</button>`;overlay.appendChild(box);document.body.appendChild(overlay);const input=box.querySelector(".tm-rand-add input"),add=box.querySelector(".tm-rand-add button");const create=()=>{const v=input.value.trim();if(!v)return;state.options.push(v.slice(0,50));input.value="";save();render();};add.addEventListener("click",create);input.addEventListener("keydown",e=>{if(e.key==="Enter")create();});box.querySelector(".tm-rand-pick").addEventListener("click",()=>{const r=box.querySelector("[data-result]");r.textContent=state.options.length?state.options[Math.floor(Math.random()*state.options.length)]:"先添加至少一个选项";});box.querySelector(".tm-rand-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"🎲",label:"随机",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-rand-style")?.remove();apiRef=null;};},open});
})();