(() => {
  "use strict";
  let apiRef=null,overlay=null,state={items:[]};
  const days=["周一","周二","周三","周四","周五","周六","周日"];
  function load(api){const s=api.storage.get({items:[]});return{items:Array.isArray(s?.items)?s.items:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){ return null; }
  function render(){const grid=overlay?.querySelector("[data-sch-grid]");if(!grid)return;grid.textContent="";days.forEach((d,i)=>{const col=document.createElement("section");col.className="tm-sch-day";const h=document.createElement("h4");h.textContent=d;col.appendChild(h);state.items.filter(x=>Number(x.day)===i).sort((a,b)=>(a.start||"").localeCompare(b.start||"")).forEach(item=>{const card=document.createElement("div");card.className="tm-sch-item";const t=document.createElement("div");t.className="tm-sch-time";t.textContent=(item.start||"")+" - "+(item.end||"");const n=document.createElement("div");n.className="tm-sch-name";n.textContent=item.title;const del=document.createElement("button");del.className="tm-sch-del";del.textContent="×";del.addEventListener("click",()=>{state.items=state.items.filter(x=>x.id!==item.id);save();render();});card.append(t,n,del);col.appendChild(card);});grid.appendChild(col);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"schedule",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-sch-ov";const box=document.createElement("section");box.className="tm-sch";box.innerHTML=`<div class="tm-sch-head"><h3>📅 日程 / 课程表</h3><button type="button">×</button></div><div class="tm-sch-add"><input maxlength="40" placeholder="课程或事件"><select></select><input type="time"><input type="time"><button type="button">添加</button></div><div class="tm-sch-grid" data-sch-grid></div>`;overlay.appendChild(box);document.body.appendChild(overlay);const title=box.querySelector('.tm-sch-add input:not([type])'),sel=box.querySelector("select"),times=box.querySelectorAll('input[type="time"]'),add=box.querySelector(".tm-sch-add button");days.forEach((d,i)=>{const o=document.createElement("option");o.value=i;o.textContent=d;sel.appendChild(o);});add.addEventListener("click",()=>{const name=title.value.trim();if(!name)return;state.items.push({id:Date.now()+Math.random(),title:name.slice(0,40),day:Number(sel.value),start:times[0].value||"",end:times[1].value||""});title.value="";save();render();});box.querySelector(".tm-sch-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"📅",label:"日程",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-schedule-style")?.remove();apiRef=null;};},open});
})();