(() => {
  "use strict";
  let apiRef=null,overlay=null,state={items:[]};
  const days=["周一","周二","周三","周四","周五","周六","周日"];
  function load(api){const s=api.storage.get({items:[]});return{items:Array.isArray(s?.items)?s.items:[]};}
  function save(){apiRef?.storage.set(state);}
  function style(){if(document.getElementById("tm-schedule-style"))return;const s=document.createElement("style");s.id="tm-schedule-style";s.textContent=`
  .tm-sch-ov{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(2,6,23,.74);backdrop-filter:blur(5px)}.tm-sch-ov.open{display:flex}
  .tm-sch{width:min(900px,97vw);max-height:90vh;overflow:auto;background:#111827;border:1px solid rgba(255,255,255,.12);border-radius:22px;color:#fff;padding:18px;font-family:"Segoe UI","Microsoft YaHei",sans-serif}.tm-sch-head{display:flex;justify-content:space-between;align-items:center}.tm-sch-head h3{margin:0}.tm-sch-head button{border:0;background:transparent;color:#94a3b8;font-size:24px;cursor:pointer}
  .tm-sch-add{display:grid;grid-template-columns:1fr 110px 100px 100px auto;gap:8px;margin:14px 0}.tm-sch-add input,.tm-sch-add select{min-width:0;border:1px solid #334155;border-radius:9px;background:#0b1220;color:#fff;padding:9px}.tm-sch-add button{border:0;border-radius:9px;background:#2563eb;color:#fff;padding:0 14px;cursor:pointer}
  .tm-sch-grid{display:grid;grid-template-columns:repeat(7,minmax(130px,1fr));gap:8px;min-width:930px}.tm-sch-day{background:rgba(30,41,59,.62);border:1px solid rgba(255,255,255,.08);border-radius:13px;padding:9px}.tm-sch-day h4{margin:0 0 8px;font-size:12px;color:#cbd5e1}.tm-sch-item{position:relative;background:#172554;border:1px solid #1d4ed8;border-radius:10px;padding:8px 24px 8px 8px;margin-bottom:6px}.tm-sch-time{font-size:10px;color:#93c5fd}.tm-sch-name{font-size:12px;margin-top:2px;word-break:break-word}.tm-sch-del{position:absolute;right:5px;top:4px;border:0;background:transparent;color:#64748b;cursor:pointer}.tm-sch-del:hover{color:#f87171}
  @media(max-width:640px){.tm-sch-add{grid-template-columns:1fr 1fr}.tm-sch-add button{padding:9px}.tm-sch-grid{min-width:820px}}
  `;document.head.appendChild(s);}
  function render(){const grid=overlay?.querySelector("[data-sch-grid]");if(!grid)return;grid.textContent="";days.forEach((d,i)=>{const col=document.createElement("section");col.className="tm-sch-day";const h=document.createElement("h4");h.textContent=d;col.appendChild(h);state.items.filter(x=>Number(x.day)===i).sort((a,b)=>(a.start||"").localeCompare(b.start||"")).forEach(item=>{const card=document.createElement("div");card.className="tm-sch-item";const t=document.createElement("div");t.className="tm-sch-time";t.textContent=(item.start||"")+" - "+(item.end||"");const n=document.createElement("div");n.className="tm-sch-name";n.textContent=item.title;const del=document.createElement("button");del.className="tm-sch-del";del.textContent="×";del.addEventListener("click",()=>{state.items=state.items.filter(x=>x.id!==item.id);save();render();});card.append(t,n,del);col.appendChild(card);});grid.appendChild(col);});}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"schedule",async mount(api){apiRef=api;state=load(api);style();overlay=document.createElement("div");overlay.className="tm-sch-ov";const box=document.createElement("section");box.className="tm-sch";box.innerHTML=`<div class="tm-sch-head"><h3>📅 日程 / 课程表</h3><button type="button">×</button></div><div class="tm-sch-add"><input maxlength="40" placeholder="课程或事件"><select></select><input type="time"><input type="time"><button type="button">添加</button></div><div class="tm-sch-grid" data-sch-grid></div>`;overlay.appendChild(box);document.body.appendChild(overlay);const title=box.querySelector('.tm-sch-add input:not([type])'),sel=box.querySelector("select"),times=box.querySelectorAll('input[type="time"]'),add=box.querySelector(".tm-sch-add button");days.forEach((d,i)=>{const o=document.createElement("option");o.value=i;o.textContent=d;sel.appendChild(o);});add.addEventListener("click",()=>{const name=title.value.trim();if(!name)return;state.items.push({id:Date.now()+Math.random(),title:name.slice(0,40),day:Number(sel.value),start:times[0].value||"",end:times[1].value||""});title.value="";save();render();});box.querySelector(".tm-sch-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});api.host.addLauncher({icon:"📅",label:"日程",onClick:open});render();return()=>{api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-schedule-style")?.remove();apiRef=null;};},open});
})();