(() => {
  "use strict";
  let apiRef=null,overlay=null,state={running:false,startAt:null,totalToday:0,date:"",history:{}},timer=null;
  const key=()=>new Date().toISOString().slice(0,10);
  function normalize(s){s=s&&typeof s==="object"?s:{};const k=key();const hist=s.history&&typeof s.history==="object"?s.history:{};let total=Number(hist[k])||0;if(s.date===k)total=Math.max(total,Number(s.totalToday)||0);return{running:Boolean(s.running),startAt:Number(s.startAt)||null,totalToday:total,date:k,history:hist};}
  function save(){state.history[state.date]=state.totalToday;apiRef?.storage.set(state);}
  function elapsed(){return state.running&&state.startAt?Math.max(0,Math.floor((Date.now()-state.startAt)/1000)):0;}
  function fmt(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");}
  function style(){ return null; }
  function commit(){if(state.running&&state.startAt){state.totalToday+=elapsed();state.running=false;state.startAt=null;save();}}
  function render(){if(!overlay)return;overlay.querySelector("[data-study-time]").textContent=fmt(state.totalToday+elapsed());overlay.querySelector("[data-study-main]").textContent=state.running?"暂停":"开始";const week=overlay.querySelector("[data-study-week]");week.textContent="";for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);const row=document.createElement("div");row.className="tm-study-row";const left=document.createElement("span");left.textContent=i===0?"今天":k;const right=document.createElement("span");right.textContent=Math.round((Number(state.history[k])||0)/60)+" 分钟";row.append(left,right);week.appendChild(row);}}
  function open(){overlay?.classList.add("open");render();}
  window.TaskMatrixPlugins.register({id:"study-timer",async mount(api){apiRef=api;state=normalize(api.storage.get({}));style();overlay=document.createElement("div");overlay.className="tm-study-ov";const box=document.createElement("section");box.className="tm-study";box.innerHTML=`<div class="tm-study-head"><h3>📚 学习时长</h3><button type="button">×</button></div><div class="tm-study-time" data-study-time>00:00:00</div><div class="tm-study-label">今天累计学习时间</div><div class="tm-study-actions"><button class="main" data-study-main>开始</button><button data-study-reset>清零今天</button></div><div class="tm-study-week" data-study-week></div>`;overlay.appendChild(box);document.body.appendChild(overlay);box.querySelector("[data-study-main]").addEventListener("click",()=>{if(state.running)commit();else{state.running=true;state.startAt=Date.now();save();}render();});box.querySelector("[data-study-reset]").addEventListener("click",()=>{state.running=false;state.startAt=null;state.totalToday=0;save();render();});box.querySelector(".tm-study-head button").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)overlay.classList.remove("open");});timer=setInterval(()=>{if(overlay?.classList.contains("open"))render();},1000);api.host.addLauncher({icon:"📚",label:"学习",onClick:open});render();return()=>{commit();clearInterval(timer);api.host.removeLauncher();overlay?.remove();overlay=null;document.getElementById("tm-study-style")?.remove();apiRef=null;};},open});
})();